### ISSUE TITLE
扫码闪退

### ISSUE THREAD

**Issue by yuan-shi** [ReaJason/WBTopicCheckTool#2]
用的最新版本，这周刚出现的情况 T.T
error message是
  File "C:\Program Files (x86)\WBTopicTool\WBTopicCheckTool-master\src\main_ui.py", line 118, in _del_scan_login
    self.log_widget.addItem(login_dict)
TypeError: arguments did not match any overloaded call:
  addItem(self, QListWidgetItem): argument 1 has unexpected type 'dict'
  addItem(self, str): argument 1 has unexpected type 'dict'

**Comment by ReaJason** [comment]
就在刚刚好像已经修复了，如果还有需求的话，可以再试试，就是原蓝奏云链接♥️

**Comment by yuan-shi** [comment]
好的，试了一下的确正常了，感谢

**Comment by yuan-shi** [comment]
> 就在刚刚好像已经修复了，如果还有需求的话，可以再试试，就是原蓝奏云链接♥️

额只是能登陆，也可以获取列表，不过签到显示的是 权限错误(382006)

**Comment by ReaJason** [comment]
> 

已修复

**Comment by yuan-shi** [comment]
> > 
> 
> 已修复

正常使用了，辛苦了
