### ISSUE TITLE
点获取二维码闪退

### ISSUE THREAD

**Issue by yuan-shi** [ReaJason/WBTopicCheckTool#4]
今天刚出现的问题，点获取二维码等了一会儿直接闪退，重新打开和重启都没有用

**Comment by ReaJason** [comment]
![image](https://user-images.githubusercontent.com/48389642/184057870-5a04c014-f8ce-45fa-9f00-4f1855e421f7.png) 我这边还能用

**Comment by yuan-shi** [comment]
> ![image](https://user-images.githubusercontent.com/48389642/184057870-5a04c014-f8ce-45fa-9f00-4f1855e421f7.png) 我这边还能用

嗯我试了下，今天可以正常用了，不清楚那天是什么情况。辛苦了
